[tool.poetry]
name = "resumedataapi"
version = "0.1.0"
description = ""
authors = ["ApprenticeofEnder <perfknight@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
django = "^4.0.5"
djangorestframework = "^3.13.1"
python-dotenv = "^0.20.0"
psycopg2-binary = "^2.9.3"
argon2-cffi = "^21.3.0"
