# Generated by Django 4.0.5 on 2022-06-24 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50)),
                ('data', models.CharField(max_length=150)),
                ('contact_name', models.CharField(max_length=50)),
            ],
        ),
    ]
