# Generated by Django 4.0.5 on 2022-06-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='link',
            field=models.CharField(default='mailto:mail@robertbabaev.tech', max_length=150),
            preserve_default=False,
        ),
    ]
